//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Chinook.Model
{
    public partial class ChinookEntities : ObjectContext
    {
        public const string ConnectionString = "name=ChinookEntities";
        public const string ContainerName = "ChinookEntities";
    
        #region Constructors
    
        public ChinookEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ChinookEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ChinookEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Album> Albums
        {
            get { return _albums  ?? (_albums = CreateObjectSet<Album>("Albums")); }
        }
        private ObjectSet<Album> _albums;
    
        public ObjectSet<Artist> Artists
        {
            get { return _artists  ?? (_artists = CreateObjectSet<Artist>("Artists")); }
        }
        private ObjectSet<Artist> _artists;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<Employee> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;
    
        public ObjectSet<Genre> Genres
        {
            get { return _genres  ?? (_genres = CreateObjectSet<Genre>("Genres")); }
        }
        private ObjectSet<Genre> _genres;
    
        public ObjectSet<Invoice> Invoices
        {
            get { return _invoices  ?? (_invoices = CreateObjectSet<Invoice>("Invoices")); }
        }
        private ObjectSet<Invoice> _invoices;
    
        public ObjectSet<InvoiceLine> InvoiceLines
        {
            get { return _invoiceLines  ?? (_invoiceLines = CreateObjectSet<InvoiceLine>("InvoiceLines")); }
        }
        private ObjectSet<InvoiceLine> _invoiceLines;
    
        public ObjectSet<MediaType> MediaTypes
        {
            get { return _mediaTypes  ?? (_mediaTypes = CreateObjectSet<MediaType>("MediaTypes")); }
        }
        private ObjectSet<MediaType> _mediaTypes;
    
        public ObjectSet<Playlist> Playlists
        {
            get { return _playlists  ?? (_playlists = CreateObjectSet<Playlist>("Playlists")); }
        }
        private ObjectSet<Playlist> _playlists;
    
        public ObjectSet<Track> Tracks
        {
            get { return _tracks  ?? (_tracks = CreateObjectSet<Track>("Tracks")); }
        }
        private ObjectSet<Track> _tracks;

        #endregion
    }
}
