//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Chinook.Model
{
    public partial class Album
    {
        #region Primitive Properties
    
        public virtual int AlbumId
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual int ArtistId
        {
            get { return _artistId; }
            set
            {
                if (_artistId != value)
                {
                    if (Artist != null && Artist.ArtistId != value)
                    {
                        Artist = null;
                    }
                    _artistId = value;
                }
            }
        }
        private int _artistId;

        #endregion
        #region Navigation Properties
    
        public virtual Artist Artist
        {
            get { return _artist; }
            set
            {
                if (!ReferenceEquals(_artist, value))
                {
                    var previousValue = _artist;
                    _artist = value;
                    FixupArtist(previousValue);
                }
            }
        }
        private Artist _artist;
    
        public virtual ICollection<Track> Tracks
        {
            get
            {
                if (_tracks == null)
                {
                    var newCollection = new FixupCollection<Track>();
                    newCollection.CollectionChanged += FixupTracks;
                    _tracks = newCollection;
                }
                return _tracks;
            }
            set
            {
                if (!ReferenceEquals(_tracks, value))
                {
                    var previousValue = _tracks as FixupCollection<Track>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTracks;
                    }
                    _tracks = value;
                    var newValue = value as FixupCollection<Track>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTracks;
                    }
                }
            }
        }
        private ICollection<Track> _tracks;

        #endregion
        #region Association Fixup
    
        private void FixupArtist(Artist previousValue)
        {
            if (previousValue != null && previousValue.Albums.Contains(this))
            {
                previousValue.Albums.Remove(this);
            }
    
            if (Artist != null)
            {
                if (!Artist.Albums.Contains(this))
                {
                    Artist.Albums.Add(this);
                }
                if (ArtistId != Artist.ArtistId)
                {
                    ArtistId = Artist.ArtistId;
                }
            }
        }
    
        private void FixupTracks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Track item in e.NewItems)
                {
                    item.Album = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Track item in e.OldItems)
                {
                    if (ReferenceEquals(item.Album, this))
                    {
                        item.Album = null;
                    }
                }
            }
        }

        #endregion
    }
}
