//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Chinook.Model
{
    public partial class Customer
    {
        #region Primitive Properties
    
        public virtual int CustomerId
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string Company
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string State
        {
            get;
            set;
        }
    
        public virtual string Country
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual string Fax
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SupportRepId
        {
            get { return _supportRepId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_supportRepId != value)
                    {
                        if (Employee != null && Employee.EmployeeId != value)
                        {
                            Employee = null;
                        }
                        _supportRepId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _supportRepId;

        #endregion
        #region Navigation Properties
    
        public virtual Employee Employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    FixupEmployee(previousValue);
                }
            }
        }
        private Employee _employee;
    
        public virtual ICollection<Invoice> Invoices
        {
            get
            {
                if (_invoices == null)
                {
                    var newCollection = new FixupCollection<Invoice>();
                    newCollection.CollectionChanged += FixupInvoices;
                    _invoices = newCollection;
                }
                return _invoices;
            }
            set
            {
                if (!ReferenceEquals(_invoices, value))
                {
                    var previousValue = _invoices as FixupCollection<Invoice>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInvoices;
                    }
                    _invoices = value;
                    var newValue = value as FixupCollection<Invoice>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInvoices;
                    }
                }
            }
        }
        private ICollection<Invoice> _invoices;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupEmployee(Employee previousValue)
        {
            if (previousValue != null && previousValue.Customers.Contains(this))
            {
                previousValue.Customers.Remove(this);
            }
    
            if (Employee != null)
            {
                if (!Employee.Customers.Contains(this))
                {
                    Employee.Customers.Add(this);
                }
                if (SupportRepId != Employee.EmployeeId)
                {
                    SupportRepId = Employee.EmployeeId;
                }
            }
            else if (!_settingFK)
            {
                SupportRepId = null;
            }
        }
    
        private void FixupInvoices(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Invoice item in e.NewItems)
                {
                    item.Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Invoice item in e.OldItems)
                {
                    if (ReferenceEquals(item.Customer, this))
                    {
                        item.Customer = null;
                    }
                }
            }
        }

        #endregion
    }
}
