//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Chinook.Model
{
    public partial class Genre
    {
        #region Primitive Properties
    
        public virtual int GenreId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Track> Tracks
        {
            get
            {
                if (_tracks == null)
                {
                    var newCollection = new FixupCollection<Track>();
                    newCollection.CollectionChanged += FixupTracks;
                    _tracks = newCollection;
                }
                return _tracks;
            }
            set
            {
                if (!ReferenceEquals(_tracks, value))
                {
                    var previousValue = _tracks as FixupCollection<Track>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTracks;
                    }
                    _tracks = value;
                    var newValue = value as FixupCollection<Track>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTracks;
                    }
                }
            }
        }
        private ICollection<Track> _tracks;

        #endregion
        #region Association Fixup
    
        private void FixupTracks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Track item in e.NewItems)
                {
                    item.Genre = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Track item in e.OldItems)
                {
                    if (ReferenceEquals(item.Genre, this))
                    {
                        item.Genre = null;
                    }
                }
            }
        }

        #endregion
    }
}
