//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Chinook.Model
{
    public partial class Track
    {
        #region Primitive Properties
    
        public virtual int TrackId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AlbumId
        {
            get { return _albumId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_albumId != value)
                    {
                        if (Album != null && Album.AlbumId != value)
                        {
                            Album = null;
                        }
                        _albumId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _albumId;
    
        public virtual int MediaTypeId
        {
            get { return _mediaTypeId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_mediaTypeId != value)
                    {
                        if (MediaType != null && MediaType.MediaTypeId != value)
                        {
                            MediaType = null;
                        }
                        _mediaTypeId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _mediaTypeId;
    
        public virtual Nullable<int> GenreId
        {
            get { return _genreId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_genreId != value)
                    {
                        if (Genre != null && Genre.GenreId != value)
                        {
                            Genre = null;
                        }
                        _genreId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _genreId;
    
        public virtual string Composer
        {
            get;
            set;
        }
    
        public virtual int Milliseconds
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Bytes
        {
            get;
            set;
        }
    
        public virtual decimal UnitPrice
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Album Album
        {
            get { return _album; }
            set
            {
                if (!ReferenceEquals(_album, value))
                {
                    var previousValue = _album;
                    _album = value;
                    FixupAlbum(previousValue);
                }
            }
        }
        private Album _album;
    
        public virtual Genre Genre
        {
            get { return _genre; }
            set
            {
                if (!ReferenceEquals(_genre, value))
                {
                    var previousValue = _genre;
                    _genre = value;
                    FixupGenre(previousValue);
                }
            }
        }
        private Genre _genre;
    
        public virtual ICollection<InvoiceLine> InvoiceLines
        {
            get
            {
                if (_invoiceLines == null)
                {
                    var newCollection = new FixupCollection<InvoiceLine>();
                    newCollection.CollectionChanged += FixupInvoiceLines;
                    _invoiceLines = newCollection;
                }
                return _invoiceLines;
            }
            set
            {
                if (!ReferenceEquals(_invoiceLines, value))
                {
                    var previousValue = _invoiceLines as FixupCollection<InvoiceLine>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInvoiceLines;
                    }
                    _invoiceLines = value;
                    var newValue = value as FixupCollection<InvoiceLine>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInvoiceLines;
                    }
                }
            }
        }
        private ICollection<InvoiceLine> _invoiceLines;
    
        public virtual MediaType MediaType
        {
            get { return _mediaType; }
            set
            {
                if (!ReferenceEquals(_mediaType, value))
                {
                    var previousValue = _mediaType;
                    _mediaType = value;
                    FixupMediaType(previousValue);
                }
            }
        }
        private MediaType _mediaType;
    
        public virtual ICollection<Playlist> Playlists
        {
            get
            {
                if (_playlists == null)
                {
                    var newCollection = new FixupCollection<Playlist>();
                    newCollection.CollectionChanged += FixupPlaylists;
                    _playlists = newCollection;
                }
                return _playlists;
            }
            set
            {
                if (!ReferenceEquals(_playlists, value))
                {
                    var previousValue = _playlists as FixupCollection<Playlist>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlaylists;
                    }
                    _playlists = value;
                    var newValue = value as FixupCollection<Playlist>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlaylists;
                    }
                }
            }
        }
        private ICollection<Playlist> _playlists;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupAlbum(Album previousValue)
        {
            if (previousValue != null && previousValue.Tracks.Contains(this))
            {
                previousValue.Tracks.Remove(this);
            }
    
            if (Album != null)
            {
                if (!Album.Tracks.Contains(this))
                {
                    Album.Tracks.Add(this);
                }
                if (AlbumId != Album.AlbumId)
                {
                    AlbumId = Album.AlbumId;
                }
            }
            else if (!_settingFK)
            {
                AlbumId = null;
            }
        }
    
        private void FixupGenre(Genre previousValue)
        {
            if (previousValue != null && previousValue.Tracks.Contains(this))
            {
                previousValue.Tracks.Remove(this);
            }
    
            if (Genre != null)
            {
                if (!Genre.Tracks.Contains(this))
                {
                    Genre.Tracks.Add(this);
                }
                if (GenreId != Genre.GenreId)
                {
                    GenreId = Genre.GenreId;
                }
            }
            else if (!_settingFK)
            {
                GenreId = null;
            }
        }
    
        private void FixupMediaType(MediaType previousValue)
        {
            if (previousValue != null && previousValue.Tracks.Contains(this))
            {
                previousValue.Tracks.Remove(this);
            }
    
            if (MediaType != null)
            {
                if (!MediaType.Tracks.Contains(this))
                {
                    MediaType.Tracks.Add(this);
                }
                if (MediaTypeId != MediaType.MediaTypeId)
                {
                    MediaTypeId = MediaType.MediaTypeId;
                }
            }
        }
    
        private void FixupInvoiceLines(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (InvoiceLine item in e.NewItems)
                {
                    item.Track = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (InvoiceLine item in e.OldItems)
                {
                    if (ReferenceEquals(item.Track, this))
                    {
                        item.Track = null;
                    }
                }
            }
        }
    
        private void FixupPlaylists(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Playlist item in e.NewItems)
                {
                    if (!item.Tracks.Contains(this))
                    {
                        item.Tracks.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Playlist item in e.OldItems)
                {
                    if (item.Tracks.Contains(this))
                    {
                        item.Tracks.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
